fun immagineImpiccato(valore:Int){
    if (valore == 0){
        println("   __________")
        println("   | /      |")
        println("   |/")
        println("   |")
        println("   |")
        println("   |")
        println("   |")
        println("___|___")
    }else if (valore == 1){
        println("   __________")
        println("   | /      |")
        println("   |/       O")
        println("   |")
        println("   |")
        println("   |")
        println("   |")
        println("___|___")
    }else if (valore == 2){
        println("   __________")
        println("   | /      |")
        println("   |/       O")
        println("   |        |")
        println("   |")
        println("   |")
        println("   |")
        println("___|___")
    }else if (valore == 3){
        println("   __________")
        println("   | /      |")
        println("   |/       O")
        println("   |       /|")
        println("   |")
        println("   |")
        println("   |")
        println("___|___")
    }else if (valore == 4){
        println("   __________")
        println("   | /      |")
        println("   |/       O")
        println("   |       /|\\")
        println("   |")
        println("   |")
        println("   |")
        println("___|___")
    }else if (valore == 5){
        println("   __________")
        println("   | /      |")
        println("   |/       O")
        println("   |       /|\\")
        println("   |       /")
        println("   |")
        println("   |")
        println("___|___")
    }else if (valore == 6){
        println("   __________")
        println("   | /      |")
        println("   |/       O")
        println("   |       /|\\")
        println("   |       / \\")
        println("   |")
        println("   |")
        println("___|___")
    }


}